version: "3"
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379